version: '3'

services:
    server_nginx:
        image: mm_server_nginx
        build:
            context: ./server/nginx
            dockerfile: Dockerfile
            args:
                HOST_DOMAIN: ${ENV_HOST_DOMAIN}
        volumes:
            - ../:/var/www:cached
            - ../var/log/nginx:/var/log/nginx:cached
        ports:
            - '80:80'
            - '8000:8000'
            - '8001:8001'
            - '5000:5000'
        networks:
            server-network:
                aliases:
                    - ${ENV_HOST_DOMAIN}
                ipv4_address: ${ENV_HOST_NGINX_IP}
        depends_on:
            - server_php_fpm_prod
            - server_php_fpm_dev
    server_node:
        image: mm_server_node-${ENV_NODE_VERSION}
        build:
            context: ../node
            dockerfile: ../docker/node/Dockerfile
            args:
                NODE_VERSION: ${ENV_NODE_VERSION}
        volumes:
            - /app/dist/node_modules
            #- /app/var/cache/node
            - ../node:/app/dist
            - ../api:/app/api
            - ../var/cache/node:/app/var/cache/node
            - ../var/log/node:/app/var/log/node
        networks:
            server-network:
                aliases:
                    - ${ENV_HOST_DOMAIN}
    server_php_fpm_prod:
        image: mm_server_php_fpm_prod-${ENV_PHP_VERSION_PROD}
        build:
            context: ./server/php
            dockerfile: Dockerfile.prod
            args:
                PHP_VERSION: ${ENV_PHP_VERSION_PROD}
                CONTAINER_USER: ${ENV_CONTAINER_USER}
                CONTAINER_USER_PID: ${ENV_CONTAINER_USER_PID}
        volumes:
            - /var/www/.git
            # - /var/www/var/cache
            #- /var/www/vendor
            - ../:/var/www
        networks:
            server-network:
                aliases:
                    - ${ENV_HOST_DOMAIN}
    server_php_fpm_dev:
        image: mm_server_php_fpm_dev-${ENV_PHP_VERSION_DEV}
        build:
            context: ./server/php
            dockerfile: ./Dockerfile.dev
            args:
                PHP_VERSION: ${ENV_PHP_VERSION_DEV}
                CONTAINER_USER: ${ENV_CONTAINER_USER}
                CONTAINER_USER_PID: ${ENV_CONTAINER_USER_PID}
        volumes:
            - /var/www/.git
            #- /var/www/var/cache
            #- /var/www/vendor
            - ../:/var/www
        networks:
            server-network:
                aliases:
                    - ${ENV_HOST_DOMAIN}

networks:
    server-network:
