ARG PHP_VERSION
FROM mm_server_php_fpm_prod-${PHP_VERSION}:latest

USER root

ARG PHP_VERSION
ARG CONTAINER_USER

# Install PHP_CodeSniffer (CONTAINER_USER LEVEL)
RUN set -uex; \
    cd /home/${CONTAINER_USER}; \
    su - ${CONTAINER_USER} -c "composer global require 'squizlabs/php_codesniffer=*'"

# install Xdebug (7.x for the version choise you have to watch .env)
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends php${PHP_VERSION}-xdebug
COPY ./config/xdebug.ini /etc/php/${PHP_VERSION}/fpm/conf.d/20-xdebug.ini
